services:
  nextjs:
    build:
      context: ./Next
      dockerfile: Dockerfile
    image: anii1802/feedlytics-nextjs:latest
    ports:
      - "3000:3000"

  services:
    build:
      context: ./Services
      dockerfile: Dockerfile
    image: anii1802/feedlytics-services:latest
    ports:
      - "3001:3001"
